markdown: kramdown
theme: minima

title: 2040FBDBIC
description: Chemo-informatics and computational drug design

minima:
  date_format: "%b %-d, %Y"
  
author:
  name: Hans De Winter
  email: "hans.dewinter@uantwerpen.be"

header_pages:
  - 01-Topic/index.md
  - 02-Topic/index.md
  - 03-Topic/index.md
  - 04-Topic/index.md

# Google Analytics measurement ID
google_analytics: G-4DZ5T3ML68
