markdown: kramdown
theme: minima

title: 2040FBDBIC
description: Chemo-informatics and computational drug design

minima:
  date_format: "%b %-d, %Y"
  
author:
  name: Hans De Winter
  email: "hans.dewinter@uantwerpen.be"

header_pages:
  - Planning.md
  - Topic_01/index.md
  - Topic_02/index.md
  - Topic_03/index.md
  - Topic_04/index.md
  - Databases.md

# Google Analytics measurement ID
google_analytics: G-4DZ5T3ML68
